# synth_check.tcl — out-of-context synthesizability check for one unit.
# Invoked by tools/run_synth_check.sh from designs/<unit>/build/:
#   vivado -mode batch -source .../synth_check.tcl -tclargs <TOP> <PART>
# Sources synth_sources.tcl (generated by /fpga-auto) from the current dir.

set TOP  [lindex $argv 0]
set PART [lindex $argv 1]

set_part $PART

# RTL hierarchy (bottom-up) + IP — written by /fpga-auto into ./synth_sources.tcl
source synth_sources.tcl

# OOC: no I/O buffer insertion, no pin constraints needed — pure synthesizability.
synth_design -top $TOP -part $PART -mode out_of_context

report_utilization -file ./synth_util.rpt
puts "SYNTH_CHECK_DONE $TOP"
