# build_bd.tcl — assemble the axis_fifo_loopback block design (IP Integrator).
#
# RUN MANUALLY (after build_ip.tcl):
#   vivado -mode batch -source build_bd.tcl
#
# Pin names below follow the FIFO Generator ports and the axis_fifo_ctrl entity;
# adjust if your IP version renames a port.

set DESIGN "axis_fifo_loopback"
create_bd_design $DESIGN

# --- FIFO IP (generated by build_ip.tcl) -----------------------------------
create_bd_cell -type ip -vlnv xilinx.com:ip:fifo_generator fifo_0
set_property -dict [list \
    CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
    CONFIG.Performance_Options {First_Word_Fall_Through} \
    CONFIG.Input_Data_Width    {64} \
    CONFIG.Input_Depth         {512} \
] [get_bd_cells fifo_0]

# --- custom controller (module reference to rtl/axis_fifo_ctrl.vhd) ---------
create_bd_cell -type module -reference axis_fifo_ctrl ctrl_0

# --- controller <-> FIFO ----------------------------------------------------
connect_bd_net [get_bd_pins ctrl_0/fifo_din]   [get_bd_pins fifo_0/din]
connect_bd_net [get_bd_pins ctrl_0/fifo_wr_en] [get_bd_pins fifo_0/wr_en]
connect_bd_net [get_bd_pins ctrl_0/fifo_full]  [get_bd_pins fifo_0/full]
connect_bd_net [get_bd_pins ctrl_0/fifo_dout]  [get_bd_pins fifo_0/dout]
connect_bd_net [get_bd_pins ctrl_0/fifo_rd_en] [get_bd_pins fifo_0/rd_en]
connect_bd_net [get_bd_pins ctrl_0/fifo_empty] [get_bd_pins fifo_0/empty]

# clocks into the FIFO
connect_bd_net [get_bd_pins ctrl_0/s_axis_aclk] [get_bd_pins fifo_0/wr_clk]
connect_bd_net [get_bd_pins ctrl_0/m_axis_aclk] [get_bd_pins fifo_0/rd_clk]

# --- external ports (discrete AXI-Stream + clocks/resets) ------------------
foreach pin { s_axis_aclk s_axis_aresetn s_axis_tdata s_axis_tvalid s_axis_tready \
              m_axis_aclk m_axis_aresetn m_axis_tdata m_axis_tvalid m_axis_tready } {
    make_bd_pins_external [get_bd_pins ctrl_0/$pin]
}

validate_bd_design
save_bd_design
make_wrapper -files [get_files ${DESIGN}.bd] -top
puts "Block design assembled: ${DESIGN} (wrapper = ${DESIGN}_wrapper)"
